#+TITLE: README
#+AUTHOR: Micky Ching
#+OPTIONS: H:4 ^:nil toc:nil
#+LATEX_CLASS: latex-doc

* Install dependencies
#+BEGIN_SRC sh
# automake/autoconf tools
sudo apt-get install build-essential libtool automake

# glib/gts library
sudo apt-get install libgts-dev libglib2.0-dev

# opengl library
sudo apt-get install freeglut3-dev libgl1-mesa-dev libglu1-mesa-dev

# boost library
sudo apt-get install libboost-dev libboost-program-options-dev

# gnuplot
sudo apt-get install gnuplot

# for metro.exe surface compare tool, if don't need compare surface,
# no need install wine
sudo apt-get install wine
#+END_SRC

* Buid and install
#+BEGIN_SRC sh
autoreconf -i
./configure
make
#+END_SRC

* Examples tools
- ioinfo :: show mesh info or convert mesh format.
- sphere :: generate sphere surface.
- offset :: coordinate transform for surface.
- simplify :: tools for simplify surface.
- milling :: maching tools for surface.
- view :: can be used to display surface or cutter path.

* Benchmark test
** Surface simplification
#+BEGIN_SRC sh
cd examples/ress
./simplify.py bunny                     # or dragon hemisphere ...
#+END_SRC

** Surface machining
#+BEGIN_SRC sh
cd examples/resm
./milling.py human                      # or sphere dragon ...
#+END_SRC

Files generated by milling.py:
- _rough_path.ilp :: rough maching cutter path for ISO-layer-path,
     can be displayed by view.
  - M-S :: save ipc to file
  - F1 :: display all layer
  - F2 :: display one layer
    - A :: show first layer
    - Z :: show last layer
    - UP :: layer up
    - DOWN :: layer down
    - a :: show first block on current layer
    - z :: show last block on current layer
    - LEFT :: reduce one block on current layer
    - RIGHT :: show one more block on current layer
- _rough_path.ipp :: rough maching cutter path for ISO-planar-path,
     can be displayed by view.
- _rough_curve.ipc :: rough maching curves for ISO-planar-path,
     can be displayed by view.
- _rough_gcode.nc :: NC G code for rough maching.

Note that milling will not only generate rough path/G-code,
it also generate finishing path/G-code.
The difference is rough milling using a cutter with bigger radius
and bigger interval.
